# parser = argparse.ArgumentParser()
# parser.add_argument("--gpu", type=int, default = 2)
# parser.add_argument("--docker", type = str2bool, default = True)
# parser.add_argument("--shared", type = str2bool, default = False)
# parser.add_argument("--lr", type = float, default = 1e-5)
# parser.add_argument("--g_lr", type = float, default = 1e-4)
# parser.add_argument("--d_lr", type = float, default = 4e-4)
# parser.add_argument("--iters", type = int, default = 10000)
# parser.add_argument("--bz", type = int, default = 300)
# parser.add_argument("--mmd_param", type = float, default = 1.0)
# parser.add_argument("--trg_clf_param", type = float, default = 1.0)
# parser.add_argument("--src_clf_param", type = float, default = 1.0)
# parser.add_argument("--scratch", type = str2bool, default = False)
# parser.add_argument("--nb_source", type = int, default = 100000)
# parser.add_argument("--nb_target", type = int, default = 100000)
# parser.add_argument("--nb_trg_labels", type = int, default = 0)
# parser.add_argument("--fc_layer", type = int, default = 128)
# parser.add_argument("--dis_fc", type = int, default = 512)
# parser.add_argument("--dis_bn", type = str2bool, default = True)
# parser.add_argument("--s_h", type = float, default = 40)
# parser.add_argument("--s_blur", type = float, default = 0.5)
# parser.add_argument("--s_noise", type = float, default = 10)
# parser.add_argument("--t_h", type = float, default = 50)
# parser.add_argument("--t_blur", type = float, default = 4.0)
# parser.add_argument("--t_noise", type = float, default = 10)
# # parser.add_argument("--clf_v", type = int, default = 1)
# # parser.add_argument("--dataset", type = str, default = 'total')
# parser.add_argument("--valid", type = int, default = 100)
# parser.add_argument("--test", type = int, default = 200)

# python adda_DA2.py --gpu 0 --docker True --dis_cnn 2 --g_cnn 6 --g_lr 1e-5 --d_lr 4e-5 --lsmooth True --dis_bn False --iters 100000 --bz 300 --dis_param 1.0 --trg_clf_param 0 --src_clf_param 3.0 --nb_trg_labels 0 --dataset total
python adda_DA.py --gpu 0 --docker True --dis_cnn 0 --dis_fc 256 --shared False --scratch False --dis_bn True